# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    dbInfo:
        class: Acme\GlobalBundle\DBinfo\DBinfos
        arguments: ["@doctrine.orm.entity_manager"]
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
